### ISSUE TITLE
Errors in Comments Box 

### ISSUE THREAD

**Issue by DavidLSC** [TLTMedia/Marginalia#106]
This Error happens when I was adding bold font and new lines.

<img width="486" alt="Screen Shot 2020-03-04 at 1 20 13 PM" src="https://user-images.githubusercontent.com/45433426/75909856-e5748200-5e1a-11ea-8f5a-ad7aff7cb732.png">

HTML tags showed in the comment box

<img width="503" alt="Screen Shot 2020-03-04 at 1 21 15 PM" src="https://user-images.githubusercontent.com/45433426/75909964-0ccb4f00-5e1b-11ea-91da-51a629c2ad46.png">

**Comment by shortland** [comment]
resolved in 9f90aa3011c11f8f9942e881990bc8220826556a
