### ISSUE TITLE
Filter is not dynamic.

### ISSUE THREAD

**Issue by DavidLSC** [TLTMedia/Marginalia#75]
Filter need to get update when the page is changed. 
e.g. Color the type filter when there is a new type, add or delete commenter when new comments are made.

**Comment by shortland** [comment]
We need to call the function `reset(comment_data)` in `FilterEvents.js`, where `comment_data` = `data` from the API request in the function `loadUserComments`.

This entails:
1. Modularize `buildHTMLFile()` then,
2. Modularize `loadUserComments()` - which has the data we then pass into `reset(comment_data)`

**Comment by shortland** [comment]
I can work on this on Monday

**Comment by shortland** [comment]
The reset() function will update the filters, given that you give it the correct data. Don't make a new function to do this

**Comment by DavidLSC** [comment]
Filter didn't change when comment is deleted, edited. I'll try call the reset at these points.

**Comment by DavidLSC** [comment]
Fixed type filter while comments getting deleted and edited. 
Commenters filter after deleting is still broken.

**Comment by shortland** [comment]
#78 78

**Comment by shortland** [comment]
Looks like you fixed 

> Filter didn't change when comment is deleted and edited.
✅Appears to be working (fixed).

**Comment by shortland** [comment]
We can close this and #78 if you think they're both good @DavidLSC
