### ISSUE TITLE
Remodularize colorNotUsedTypeSelector()

### ISSUE THREAD

**Issue by shortland** [TLTMedia/Marginalia#78]
don't let it call get_highlights,... pass in that info from elsewhere. (we have it! - i think!)

**Comment by DavidLSC** [comment]
Do u mean call a function from the modules or pass in the whole highlight data

**Comment by shortland** [comment]
Put this function inside a module & pass in the whole highlight data instead of function making an API request.

Because /get_highlights endpoint is already & it's data used for dynamic filter. So we can pass it to this function too, instead of calling the endpoint twice. (I think if I remember correctly)

**Comment by DavidLSC** [comment]
Made new function `colorNotUsedTypeSelector(work_comment_data)`

**Comment by shortland** [comment]
ef36153

**Comment by shortland** [comment]
and removal in ac99cb8

**Comment by shortland** [comment]
@DavidLSC I mostly just committed and pushed your code here. Test if it works and we can close? I don't remember everything we needed to test.

**Comment by shortland** [comment]
`colorNotUsedTypeSelector ` was modularized and renamed `color_not_used_type_selector`
