### ISSUE TITLE
Highlighting can take awhile if there's a lot of highlights

### ISSUE THREAD

**Issue by shortland** [TLTMedia/Marginalia#79]
Load this page: https://apps.tlt.stonybrook.edu/marginalia/#/get_work/CSE%20337.01%20-%20Fall_2019/ikleiman@stonybrook.edu/Ilan%20Kleiman_110942711_Minor%20HW%202

If you change the filter to "Historical" it takes a bit of time to render the highlights. I checked the network and the backend is responding quickly (~32ms) - so the frontend is bottlenecking when we try to render a lot of highlights.

**Comment by DavidLSC** [comment]
I found out that it calls the same function twice when we choose a filter option. I already fix it.
