### ISSUE TITLE
Error on either delete_comment API or get_comment_chain

### ISSUE THREAD

**Issue by DavidLSC** [TLTMedia/Marginalia#89]
<img width="506" alt="Screen Shot 2020-02-11 at 3 36 21 PM" src="https://user-images.githubusercontent.com/45433426/74276734-44474f80-4ce4-11ea-8fdc-8b53781f83c1.png">
 Delete comment api should delete the comment ID for the deleted comments, however the data get_comment_chain returned didn't updated the comment ID. So the tool bar still shows up when the comment is deleted.

**Comment by shortland** [comment]
is this not an error with backend?
